const commentsArray = ["Early 90's in Sweden I learned about \"ättestupa\" - the viking practice of seniors throwing themselves/being thrown down cliffs when the…", "Rosa Parks wasn’t the first to refuse to sit in the back of the bus. Shout out to Claudette Colvin!", "In 7th grade my geography teacher taught us that China had such a big population because of the Asian monsoons (which basically means th…", "Battle of Wounded Knee. It wasn’t a battle, it was a massacre. Also, my class only really mentioned the number of American soldier…", "I had a teacher in the 90s laugh at me when I said I didnt think currencies needed to be tied to gold.↵↵He didnt know the gold standar…", "In the Philippines, that Filipinos invented the fluorescent bulb and karaoke.", "D.A.R.E. taught me that people would be offering me free drugs everywhere. Boy were they wrong.", "That Thomas Edison invented the light bulb.", "I told my son who was studying about a country's history and the teacher sent a homework about one of their castles saying it was from th…", "I’m a teacher so I like to check myself when I say something that they’re surprised by. Recently I found out that Black Widow spiders onl…", "That the dollar sign is a U superimposed on an S, that stands for the United States.  The Symbol predates the US.", "Turns out the American Civil War was not a result of “Abraham Lincoln being a poopy-head”.  Gotta thank the Mississippi school system fo…", "The discovery of America. Columbus was FAR from the wide-eyed visionary explorer children's books make him out to be. Very, very far.", "The “war of northern aggression” is actually colloquially called the Civil War.", "Tulsa?  Nothing happened in Tulsa - check your history book", "*”Listen, my children, and you shall hear of the midnight ride of Paul Revere”*↵↵↵Paul Revere rode approximately 20 miles from Boston t…", "Tastebuds. I vividly remember a textbook saying that since we had the soft spot at the tip of the tongue, we liked licking ice creams an…", "Eating carrots helps your night vision.", "who else here was raised in the 80s where the Food Pyramid was drilled into your head?  I've known longer that it's hogwash than I 'lived…", "Peaceful negotiation only happens after a long period of violence and unrest until the colonialist find themselves on the losing end. Ain'…", 
"Lot of Columbus hate in here, and for good reason. But I'd just like to add that the impression I got in school was that the Nativ…", "That if you did something blatantly illegal, the cops would arrest you", "That the Pilgrims came over to America for “religious freedom”.  Painted them as these kind of progressive liberal Christians and acros…", "\"Nobody knows what killed the dinosaurs\"", "Young George Washington and the cherry tree. That story was in textbooks in our elementary school.", "For Czech, that the Hussite wars were over Czech nationalism, I mean they weren’t really, they’re a basis of our nationalism but tbh it wa…", "Slave in the American South were largely treated like members of the family.", "That Puritans left England due to religious persecution.  I just learned that the Puritans were against any other religion and left Englan…", "My middle school history teacher was adamant that the Civil War was over state's rights and not slavery..", "The idea of checks and balances in the government", "That nobody walks around with a calculator in their pocket...", "That buffalo were not hunted to extinction in the 1800s. I probably just misunderstood but this shattered my perception of American histor…", "Being from Texas I learned that the \"Texians,\" that is, American colonists who came to Texas, fought for their freedom against a tyrannica…", "That slavery wasn't that bad, And sometimes they had a picnic!", "Quicksand was a threat out to kill me and everyone I love.", "I remember doing something in primary school (about 7-8year old) on explorers. ↵↵This included that Columbus was European in America an…", "(about the Battle of Stalingrad) \"The People of Stalingrad, as one, stood up and told the fascist invader 'no, you shall not take the cit…", "That Truganini was the Last Tasmanian Aboriginal. There is still a proud Tasmanian Aboriginal community. \"Pure blood\" does not matter.", "That where the bible said Adam donated a rib to make Eve, it said it as a theological way of explaining “why men have fewer ribs tha…", "That when John F Kennedy said 'Ich bin ein Berliner' he was unintentionally saying 'I am a doughnut'.  This was a rumour that came abou…", "Nero setting Rome on fire and the political structure of Feudalism.", "Sojourner Truth's famous \"Ain't I a woman\" speech never happened, at least not the way it's presented.↵↵She was actually born and raised i…"]



const postsArray = [
    {author: "HeadSavings1410", 
    permalink: "/r/AskReddit/comments/1jb7l5n/musk_keeps_amplifying_the_impeachment_of_judges/", 
    score: 3546, 
    subreddit: "AskReddit", 
    title: "Musk keeps amplifying the impeachment of judges who rule against his doge policies, so what do any constitutional Republicans have to sa…", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb7l5n/musk_keeps_amplifying_the_impeachment_of_judges/", 
    created: 1741968684, 
    num_comments: 484}, 
    {author: "vn66", 
    permalink: "/r/AskReddit/comments/1jb2jea/what_historical_fact_did_you_learn_in_school_that/", 
    score: 3321, 
    subreddit: "AskReddit", 
    title: "What historical \"fact\" did you learn in school, that later turned out to be completely wrong or misrepresented?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb2jea/what_historical_fact_did_you_learn_in_school_that/", 
    created: 1741954645, 
    num_comments: 3528}, 
    {author: "thepoutingmom", 
    permalink: "/r/AskReddit/comments/1jbb6bf/whos_an_actor_who_nailed_a_role_so_hard_that/", 
    score: 898, 
    subreddit: "AskReddit", 
    title: "Who's an actor who nailed a role so hard that nobody else will ever be able to live up to it?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jbb6bf/whos_an_actor_who_nailed_a_role_so_hard_that/", 
    created: 1741978266, 
    num_comments: 3158}, 
    {author: "Love-Sierra", 
    permalink: "/r/AskReddit/comments/1jbca57/what_comedian_has_so_much_hype_but_you_dont_think/", 
    score: 289, 
    subreddit: "AskReddit", 
    title: "What comedian has so much hype but you don’t think is actually funny?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jbca57/what_comedian_has_so_much_hype_but_you_dont_think/", 
    created: 1741981049, 
    num_comments: 1018}, 
    {author: "Saul_goodmannnnn", 
    permalink: "/r/AskReddit/comments/1jawh29/people_who_had_a_onenight_stand_that_turned_into/", 
    score: 3887, 
    subreddit: "AskReddit", 
    title: "People who had a 'one-night stand' that turned into an actual nightmare—what happened?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jawh29/people_who_had_a_onenight_stand_that_turned_into/", 
    created: 1741929118, 
    num_comments: 1612}, 
    {author: "BisonNo9004", 
    permalink: "/r/AskReddit/comments/1jaxosu/whats_a_modern_convenience_that_actually_made/", 
    score: 2761,
    subreddit: "AskReddit", 
    title: "What's a 'modern convenience' that actually made your life harder?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jaxosu/whats_a_modern_convenience_that_actually_made/", 
    created: 1741934407, 
    num_comments: 2159}, 
    {author: "Potential_Sky_35", 
    permalink: "/r/AskReddit/comments/1jb0c4g/whats_the_best_relationship_tip_you_can_give_that/", 
    score: 1104, 
    subreddit: "AskReddit", 
    title: "What’s the best relationship tip you can give that creates healthy relationship?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb0c4g/whats_the_best_relationship_tip_you_can_give_that/", 
    created: 1741946281, 
    num_comments: 392}, 
    {author: "Saul_goodmannnnn", 
    permalink: "/r/AskReddit/comments/1jawjvd/those_who_have_been_clinically_dead_and_came/", 
    score: 2651, 
    subreddit: "AskReddit", 
    title: "Those who have been clinically dead and came back—what did you see??", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jawjvd/those_who_have_been_clinically_dead_and_came/", 
    created: 1741929429, 
    num_comments: 643}, 
    {author: "Kinglycole", 
    permalink: "/r/AskReddit/comments/1jb83a7/whats_something_everyone_else_seems_to_get_but_is/", 
    score: 300, 
    subreddit: "AskReddit", 
    title: "What’s something everyone else seems to get but is a foreign concept to you?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb83a7/whats_something_everyone_else_seems_to_get_but_is/", 
    created: 1741969973, 
    num_comments: 686}, 
    {author: "one-droplet", 
    permalink: "/r/AskReddit/comments/1jaqvc0/what_are_the_early_signs_of_a_failing/", 
    score: 3630, 
    subreddit: "AskReddit", 
    title: "What are the early signs of a failing relationship that most people ignore?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jaqvc0/what_are_the_early_signs_of_a_failing/", 
    created: 1741910945, 
    num_comments: 583}, 
    {author: "Picard42069", 
    permalink: "/r/AskReddit/comments/1jb0p0x/whats_the_best_advice_anyone_ever_gave_you/", 
    score: 432, 
    subreddit: "AskReddit", 
    title: "What’s the best advice anyone ever gave you?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb0p0x/whats_the_best_advice_anyone_ever_gave_you/", 
    created: 1741947794, 
    num_comments: 526}, 
    {author: "splitopenandmelt11", 
    permalink: "/r/AskReddit/comments/1jamhak/people_over_35_what_do_you_personally_spend_your/", 
    score: 4660, 
    subreddit: "AskReddit", 
    title: "People over 35, what do you personally spend your expendable income on?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jamhak/people_over_35_what_do_you_personally_spend_your/", 
    created: 1741899256, 
    num_comments: 8777}, 
    {author: "Fifa15Stan", 
    permalink: "/r/AskReddit/comments/1jat6kw/whats_a_conspiracy_theory_youve_heard_that_seems/", 
    score: 1522, 
    subreddit: "AskReddit", 
    title: "What’s a conspiracy theory you’ve heard that seems way more believable the more you look into it?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jat6kw/whats_a_conspiracy_theory_youve_heard_that_seems/", 
    created: 1741917908, 
    num_comments: 3125}, 
    {author: "No-Department2", 
    permalink: "/r/AskReddit/comments/1jb8mt2/what_did_you_want_to_be_when_you_grew_up_and_what/", 
    score: 91, 
    subreddit: "AskReddit", 
    title: "What did you want to be when you grew up? And what are you now?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb8mt2/what_did_you_want_to_be_when_you_grew_up_and_what/", 
    created: 1741971373, 
    num_comments: 566}, 
    {author: "OKJOKER0771", 
    permalink: "/r/AskReddit/comments/1jb4gmv/if_you_could_delete_one_profession_from_existence/", 
    score: 136, 
    subreddit: "AskReddit", 
    title: "If you could delete one profession from existence with zero consequences, what would it be?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb4gmv/if_you_could_delete_one_profession_from_existence/", 
    created: 1741960516, 
    num_comments: 846}, 
    {author: "The_Burning_Face", 
    permalink: "/r/AskReddit/comments/1jb04p6/why_do_you_think_houses_are_only_ever_haunted_by/", 
    score: 273, 
    subreddit: "AskReddit", 
    title: "Why do you think houses are only ever haunted by people from the Victorian\\American civil war era? Why are houses never haunted by som…", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb04p6/why_do_you_think_houses_are_only_ever_haunted_by/", 
    created: 1741945355, 
    num_comments: 137}, 
    {author: "King66760", 
    permalink: "/r/AskReddit/comments/1jb3q7c/what_would_you_like_your_last_words_to_be/", 
    score: 135, 
    subreddit: "AskReddit", 
    title: "What would you like your last words to be?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb3q7c/what_would_you_like_your_last_words_to_be/", 
    created: 1741958390, 
    num_comments: 547}, 
    {author: "Prestigious_Wait_251", 
    permalink: "/r/AskReddit/comments/1jaxbf3/if_you_could_go_anywhere_in_the_universe_in_a/", 
    score: 472, 
    subreddit: "AskReddit", 
    title: "If you could go anywhere in the universe in a protective bubble, where would you go?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jaxbf3/if_you_could_go_anywhere_in_the_universe_in_a/", 
    created: 1741932722, 
    num_comments: 274}, 
    {author: "Vetro_nodulare", 
    permalink: "/r/AskReddit/comments/1jb8gw1/whats_the_prettiest_name_you_have_ever_heard/", 
    score: 62, 
    subreddit: "AskReddit", 
    title: "What's the prettiest name you have ever Heard?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb8gw1/whats_the_prettiest_name_you_have_ever_heard/", 
    created: 1741970960, 
    num_comments: 564}, 
    {author: "CalyraVen", 
    permalink: "/r/AskReddit/comments/1jb9rjs/whats_something_incredibly_dangerous_that_most/", 
    score: 54, 
    subreddit: "AskReddit", 
    title: "What's something incredibly dangerous that most people don't take seriously?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb9rjs/whats_something_incredibly_dangerous_that_most/", 
    created: 1741974144, 
    num_comments: 255}, 
    {author: "SirFrankerZ", 
    permalink: "/r/AskReddit/comments/1jafnvj/whats_an_underrated_pizza_topping/", 
    score: 6181, 
    subreddit: "AskReddit", 
    title: "What's an underrated pizza topping?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jafnvj/whats_an_underrated_pizza_topping/", 
    created: 1741882328, 
    num_comments: 13067}, 
    {author: "ADHD-Distraction", 
    permalink: "/r/AskReddit/comments/1jbb328/what_is_something_you_refuse_to_accept/", 
    score: 34, 
    subreddit: "AskReddit", 
    title: "What is something you refuse to accept?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jbb328/what_is_something_you_refuse_to_accept/", 
    created: 1741978028, 
    num_comments: 226}, 
    {author: "dunno--00", 
    permalink: "/r/AskReddit/comments/1japrfd/which_celebrity_death_during_your_lifetime_that/", 
    score: 961, 
    subreddit: "AskReddit", 
    title: "Which celebrity death during your lifetime that hit you the hardest?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1japrfd/which_celebrity_death_during_your_lifetime_that/", 
    created: 1741907813, 
    num_comments: 8257}, 
    {author: "Barbarossabros", 
    permalink: "/r/AskReddit/comments/1jb1cxc/what_triggers_your_anxiety/", 
    score: 104, 
    subreddit: "AskReddit", 
    title: "What triggers your anxiety?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jb1cxc/what_triggers_your_anxiety/", 
    created: 1741950524, 
    num_comments: 536}, 
    {author: "VirtuaHealth", 
    permalink: "/r/AskReddit/comments/1jajluk/whats_a_common_health_myth_that_needs_to_go_away/", 
    score: 1931, 
    subreddit: "AskReddit", 
    title: "What’s a common health myth that needs to go away already?", 
    url: "https://www.reddit.com/r/AskReddit/comments/1jajluk/whats_a_common_health_myth_that_needs_to_go_away/", 
    created: 1741892011, 
    num_comments: 2328}
];

const subredditArray = [
    {banner_background_color: "", 
        banner_background_image: "", 
    banner_image: undefined, 
    description: "Everything home related: interior design, home improvement, architecture.↵↵**Related subreddits**↵--------------------------↵…", 
    display_name_prefixed: "r/Home", 
    title: "Home", 
    url: "/r/Home/", 
    created: 1232850357, 
    subreddit_type: "public", 
    community_icon: "", 
    subscribers: 289605}, 
    {banner_background_color: "#d4eaff", 
        banner_background_image: "", 
        banner_image: undefined, 
        description: "###### [ [ SERIOUS ] ](http://www.reddit.com/r/askreddit/submit?selftext=true&amp;title=%5BSerious%5D)\r↵\r↵\r↵####…", 
        display_name_prefixed: "r/AskReddit", 
        title: "Ask Reddit...", 
        url: "/r/AskReddit/", 
        created: 1201233135, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2qh1i/styles/communityIcon_p6kb2m6b185b1.png?width=256&amp;s=c28b9f038c305e139b62739f2133d7b776582696", 
        subscribers: 52758391}, 
    {banner_background_color: "#0079d3", 
        banner_background_image: "https://styles.redditmedia.com/t5_2w844/styles/bannerBackgroundImage_k7ndz0eykl191.jpg?width=4000&amp;s=6ffc54d4a94c6573fbbe5a8f7f82e79519fe…", 
        banner_image: undefined, 
        description: "###There is no such thing as a Stupid Question!↵↵Don't be embarrassed of your curiosity; everyone has questions that they may fee…", 
        display_name_prefixed: "r/NoStupidQuestions", 
        title: "No such thing as stupid questions", 
        url: "/r/NoStupidQuestions/", 
        created: 1359795144, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2w844/styles/communityIcon_krq4riav5m191.png?width=256&amp;s=3bb045009d2a9d1d7543dc7afb7b53a0e6f18121", 
        subscribers: 5580183}, 
    {banner_background_color: "", 
        banner_background_image: "https://styles.redditmedia.com/t5_12967t/styles/bannerBackgroundImage_ygkze629sv6c1.png?width=4000&amp;s=ad8cf22d3cf91fafcdfc82b21f2d8c41ae0…", 
        banner_image: undefined, 
        description: "A community all about *Baldur's Gate III*, the role-playing video game by Larian Studios. BG3 is the third main game in the *Baldur's Gate…",
        display_name_prefixed: "r/BaldursGate3", 
        title: "Baldur's Gate 3", 
        url: "/r/BaldursGate3/", 
        created: 1559226938, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_12967t/styles/communityIcon_rh7ocpigb9t51.png?width=256&amp;s=fc8ce762012139f5f4bb3fe341ec1676e175e7b3", 
        subscribers: 2913200}, 
    {banner_background_color: "", 
        banner_background_image: "https://styles.redditmedia.com/t5_2r5rp/styles/bannerBackgroundImage_xjz99n5qt8p61.png?width=4000&amp;s=2b8ed87d76b7a6854c822e2da2c79fbc01ce…", 
        banner_image: undefined, 
        description: "[Click here to not view Coronavirus posts](https://www.reddit.com/r/facepalm/search?q=NOT+flair%3ACoronavirus&amp;restrict_sr=on&amp;include…", 
        display_name_prefixed: "r/facepalm", 
        title: "now double verified", 
        url: "/r/facepalm/", 
        created: 1251449390, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2r5rp/styles/communityIcon_2c4ms7mggreb1.png?width=256&amp;s=52dbbe21d1959c3d4419cf578e179584d40f9ba4", 
        subscribers: 8166724}, 
    {banner_background_color: "#ff66ac", 
        banner_background_image: "https://styles.redditmedia.com/t5_2qhsa/styles/bannerBackgroundImage_3498khtiddlb1.png?width=4000&amp;s=bc4b3e3fa00409ab18c8de7d71d71a9012ac…", 
        banner_image: undefined, 
        description: "---↵↵A place to share (almost) anything and everything interesting as fuck.↵↵---↵↵# [Please read ou…", 
        display_name_prefixed: "r/interestingasfuck", 
        title: "Interesting As Fuck", 
        url: "/r/interestingasfuck/", 
        created: 1207822208, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2qhsa/styles/communityIcon_zp89zqe7cdlb1.png?width=256&amp;s=12f80fb9ec0476fa93e9b4fc2e14a9a49c172d22", 
        subscribers: 13537215}, 
    {banner_background_color: "", 
        banner_background_image: "", 
        banner_image: undefined, 
        description: "[Image](http://www.reddit.com/r/damnthatsinteresting/search?q=flair%3A%27Image%27&amp;restrict_sr=on&amp;sort=new&amp;t=all…", 
        display_name_prefixed: "r/Damnthatsinteresting", 
        title: "Damn, that's interesting!", 
        url: "/r/Damnthatsinteresting/", 
        created: 1374425825, 
        subreddit_type: "public", 
        community_icon: "", 
        subscribers: 19637406}, 
    {banner_background_color: "", 
        banner_background_image: "https://styles.redditmedia.com/t5_38jf0/styles/bannerBackgroundImage_ppth0rv384le1.png?width=4000&amp;s=5e4afbd0349878e3a755ecfedb8f71b95cf7…", 
        banner_image: undefined, 
        description: "---↵ ↵##Welcome↵ ↵* Welcome to /r/LivestreamFail: the place for almost anything livestream related.↵↵* Please read our rule…", 
        display_name_prefixed: "r/LivestreamFail", 
        title: "r/LivestreamFail", 
        url: "/r/LivestreamFail/", 
        created: 1433716387, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_38jf0/styles/communityIcon_e62np5szn0sc1.png?width=256&amp;s=2540390dea9eac7598053fd60d973e8f9edf68ef", 
        subscribers: 3857444}, 
    {banner_background_color: "#5a74cc", 
        banner_background_image: "https://styles.redditmedia.com/t5_2qh0u/styles/bannerBackgroundImage_if1cbgj4mc7b1.jpg?width=4000&amp;s=f6831859646d3127e64749644e05d129279a…", 
        banner_image: undefined, 
        description: "[Please read our rules in their entirety before participating.](/r/pics/wiki/index)↵↵1. No screenshots, AI images, or pictures in which th…", 
        display_name_prefixed: "r/pics", 
        title: "Reddit Pics", 
        url: "/r/pics/", 
        created: 1201221069, 
        subreddit_type: "public", 
        community_icon: "", 
        subscribers: 31730361}, 
    {banner_background_color: "#000000", 
        banner_background_image: "https://styles.redditmedia.com/t5_4jn9v4/styles/bannerBackgroundImage_si4szqp3306d1.jpeg?width=4000&amp;s=22fa3e00fb913a969547c6c99015ef75c8…", 
        banner_image: undefined, 
        description: "Palworld is a brand-new, multiplayer, open-world survival crafting game where you can befriend and collect mysterious creatures calle…", 
        display_name_prefixed: "r/Palworld", 
        title: "Palworld", 
        url: "/r/Palworld/", 
        created: 1622895564, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_4jn9v4/styles/communityIcon_6ms02ql8avec1.png?width=256&amp;s=6d07cddd535495c488d9e90cec2fd095a224a0d4", 
        subscribers: 712388}, 
    {banner_background_color: "", 
        banner_background_image: "https://styles.redditmedia.com/t5_2xhvq/styles/bannerBackgroundImage_nacao2gsxu321.jpg?width=4000&amp;s=b2f2fab5fd103ffdaa55aab2ac979d3c5225…", 
        banner_image: undefined, 
        description: "#Welcome to r/AmITheAsshole!↵↵A catharsis for the frustrated moral philosopher in all of us, and a place to finally find out if you wer…", 
        display_name_prefixed: "r/AmItheAsshole", 
        title: "Am I the Asshole? ", 
        url: "/r/AmItheAsshole/", 
        created: 1370722490, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2xhvq/styles/communityIcon_8qil7zgp7oh81.png?width=256&amp;s=28d683e0a56bac45348aefb016b19e0852c8bfd6", 
        subscribers: 24073715}, 
    {banner_background_color: "#ff8717", 
        banner_background_image: "https://styles.redditmedia.com/t5_2ubgg/styles/bannerBackgroundImage_qhj1ts036d811.jpg?width=4000&amp;s=9ec82657c01b5ddefb4be5b878f0a87dfe0e…", 
        banner_image: undefined, 
        description: "&gt;[](https://td.reddit.com/r/mildlyinfuriating/#image)↵[Enter mildyinfuriating &amp;nbsp; &amp;nbsp;( ͡° ͜…", 
        display_name_prefixed: "r/mildlyinfuriating", 
        title: "jukmifgguggh", 
        url: "/r/mildlyinfuriating/", 
        created: 1339961663, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2ubgg/styles/communityIcon_lkxajjefezh51.png?width=256&amp;s=7bb81fe43583d4a482979e0e54e1c14ef94ac580", 
        subscribers: 9537390}, 
    {banner_background_color: "#182d40", 
        banner_background_image: "https://styles.redditmedia.com/t5_2qmox/styles/bannerBackgroundImage_hjuavt6lntud1.png?width=4000&amp;s=0d8dce5248da41b99a7c9e503d939f72abcc…", 
        banner_image: undefined, 
        description: "# Filter by Flair↵↵Flair | Filter↵---|---↵[Announcement](https://old.reddit.com/r/Piracy/search?q=flair_name%3A%22Announcement%22&amp;restri…", 
        display_name_prefixed: "r/Piracy", 
        title: "Piracy: ꜱᴀɪʟ ᴛʜᴇ ʜɪɢʜ ꜱᴇᴀꜱ", 
        url: "/r/Piracy/", 
        created: 1221893014, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2qmox/styles/communityIcon_i9fccrqzl8ae1.png?width=256&amp;s=25af0859be48b7cb1f9836ff79fce10038ac481d", 
        subscribers: 2105822}, 
    {banner_background_color: "#bbbdbf", 
        banner_background_image: "https://styles.redditmedia.com/t5_121h8r/styles/bannerBackgroundImage_cvk21hdu7pu31.png?width=4000&amp;s=17fb0e6c1fb223ea1dfddb286f9c5a4c635…", 
        banner_image: undefined, 
        description: "The subreddit for honoring our hero u/PeterExplainsTheJoke whenever we don't understand it.", 
        display_name_prefixed: "r/PeterExplainsTheJoke", 
        title: "PeterExplainsTheJoke", 
        url: "/r/PeterExplainsTheJoke/", 
        created: 1558894980, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_121h8r/styles/communityIcon_16sx91he4iq71.jpg?width=256&amp;s=0176cdadd7fcb3ee60ab162496a8ae767177ebfc", 
        subscribers: 1235100}, 
    {banner_background_color: "", 
        banner_background_image: "", 
        banner_image: undefined, 
        description: "**Welcome to r/Funny:**↵↵↵You may only post if you are funny. ↵↵↵**Please read [our complete rule…", 
        display_name_prefixed: "r/funny", 
        title: "funny", 
        url: "/r/funny/", 
        created: 1201242956, 
        subreddit_type: "public", 
        community_icon: "", 
        subscribers: 66546551}, 
    {banner_background_color: "", 
        banner_background_image: "", 
        banner_image: undefined, 
        description: "this is a community like r/AmITheAsshole except unlike that subreddit here you can post interpersonal conflicts, anything that's AITA bu…", 
        display_name_prefixed: "r/AITAH", 
        title: "AITAH", 
        url: "/r/AITAH/", 
        created: 1615939521, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_446kys/styles/communityIcon_a7690j16och91.png?width=256&amp;s=0a95f7763288bbf5f3c0a78ac91988c722e32f9c", 
        subscribers: 3455371}, 
    {banner_background_color: "#373c3f", 
        banner_background_image: "https://styles.redditmedia.com/t5_2qh3s/styles/bannerBackgroundImage_k1ukyjei82r81.png?width=4000&amp;s=731749ec0839e557c7bf41ec21beae0f083e…", 
        banner_image: undefined, 
        description: "[](#/RES_SR_Config/NightModeCompatible)↵↵&gt; &gt; [**Our Full Rules an…", 
        display_name_prefixed: "r/movies", 
        title: "Movie News and Discussion", 
        url: "/r/movies/", 
        created: 1201243950, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2qh3s/styles/communityIcon_3hssuqq28v4e1.png?width=256&amp;s=6974f29dca55ef7e8cce5bfe78de2c415d49a747", 
        subscribers: 34718579}, 
    {banner_background_color: "#373c3f", 
        banner_background_image: "https://styles.redditmedia.com/t5_2ya0t/styles/mobileBannerImage_g2ntf6vtisie1.png?width=4000&amp;s=a4016e968dd4228433f381f2052c2c331e81cdb6", 
        banner_image: undefined, 
        description: "A subreddit dedicated to HELLDIVERS and HELLDIVERS 2, intense co-op shooters set in a satirical dystopian future where you play as one o…", 
        display_name_prefixed4: "r/Helldivers", 
        title: "Helldivers", 
        url: "/r/Helldivers/", 
        created: 1377154242, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2ya0t/styles/communityIcon_ql5iyxjfuvic1.jpg?width=256&amp;s=0a8da2f628b9191b6a6ebaddd084d0d4dc9cbd2c", 
        subscribers: 1928091}, 
    {banner_background_color: "#373c3f", 
        banner_background_image: "https://styles.redditmedia.com/t5_2qh03/styles/bannerBackgroundImage_j84aqdq3eyd91.png?width=4000&amp;s=750c0c8fac9a435d86f5884c01db442811a2…", 
        banner_image: undefined, 
        description: "**If your submission does not appear, do not delete it. Simply [message th…", 
        display_name_prefixed: "r/gaming", 
        title: "r/gaming", 
        url: "/r/gaming/", 
        created: 1190054605, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2qh03/styles/communityIcon_1isvxgkk7hw51.png?width=256&amp;s=b2c4017083ea0176a3dd4837f6e009bbc8384f15", 
        subscribers: 45857464}, 
    {banner_background_color: "#cee3f8", 
        banner_background_image: "https://styles.redditmedia.com/t5_2qh13/styles/bannerBackgroundImage_5q0f5lsk6pu01.png?width=4000&amp;s=e458bb009e1685c46f945a93af462cc2e252…", 
        banner_image: undefined, 
        description: "&gt;&gt;&gt; - **Other Subs:**↵↵&gt;&gt;&gt; - [Related](http://goo.gl/ztbbza)↵&gt;&gt;&gt;     - /r/News↵&gt;&gt;&gt;     - /r/geopolitic…", 
        display_name_prefixed: "r/worldnews", 
        title: "World News", 
        url: "/r/worldnews/", 
        created: 1201231119, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2qh13/styles/communityIcon_pldiwqvsyns91.png?width=256&amp;s=1e3f0453042ba59e08945b2beab03f408a4135e4", 
        subscribers: 44666109}, 
    {banner_background_color: "#373c3f", 
        banner_background_image: "https://styles.redditmedia.com/t5_2rfxx/styles/bannerBackgroundImage_n6f4p8p3dyqd1.jpg?width=4000&amp;s=82c377ecdf69c51d12c23b72f01f06b69c65…", 
        banner_image: undefined, 
        description: "1. **[Patch 25.S1.5 Bug Megathread](https://www.reddit.com/r/leagueoflegends/comments/1j3p1ug/patch_25s15_bug_megathread/)**↵…", 
        display_name_prefixed: "r/leagueoflegends", 
        title: "League of Legends", 
        url: "/r/leagueoflegends/", 
        created: 1263422348, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2rfxx/styles/communityIcon_9yj66cjf8oq61.png?width=256&amp;s=c0afcd1490e52c1641a698b5453570b7bec50b11", 
        subscribers: 8055903}, 
    {banner_background_color: "#373c3f", 
        banner_background_image: "https://styles.redditmedia.com/t5_2sgp1/styles/bannerBackgroundImage_mgz30o28keh81.png?width=4000&amp;s=5b7790db1bd9e6d29b36523715fda37f2b4c…", 
        banner_image: undefined, 
        description: "1. [**Why PC?**](https://pcmasterrace.org/guide)\r↵1. [**Builds**](https://pcmasterrace.org/builds)\r↵1…", 
        display_name_prefixed: "r/pcmasterrace", 
        title: "PC Master Race - PCMR: A place where all enthusiasts of PC, PC gaming and PC technology are welcome!", 
        url: "/r/pcmasterrace/", 
        created: 1304179207, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2sgp1/styles/communityIcon_1mit7n6qhy481.png?width=256&amp;s=b693ef2414ef97485151d9140733c025405e027b", 
        subscribers: 14682440}, 
    {banner_background_color: "", 
        banner_background_image: "https://styles.redditmedia.com/t5_2w67q/styles/bannerBackgroundImage_mhrbmvrsdrce1.png?width=4000&amp;s=e6ebda61c5b392aa7e4db01aedcf49828338…", 
        banner_image: undefined, 
        description: "**Rules:**  ↵↵https://www.reddit.com/r/Unexpected/about/rules/↵↵   ↵Please look through our [To…", 
        display_name_prefixed: "r/Unexpected", 
        title: "Unexpected", 
        url:  "/r/Unexpected/", 
        created: 1359322704, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2w67q/styles/communityIcon_9cgp16ko1rce1.png?width=256&amp;s=e3c65f3afe7face12169433b7ebe08ec003ada7c", 
        subscribers: 11491481}, 
    {banner_background_color: "#192939", 
        banner_background_image: "", 
        banner_image: undefined, 
        description: "&gt;* **[/r/worldnews](/r/worldnews?hl)**↵↵&gt;#↵↵&gt;* **[/r/politics](/r/politics?hl)**↵↵&gt;#↵↵&gt;…", 
        display_name_prefixed: "r/news", 
        title: "News", 
        url: "/r/news/", 
        created: 1201243765, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2qh3l/styles/communityIcon_fmygcobc22z81.png?width=256&amp;s=20360f000285c26be3d504fdb0cc8e6d6d58289c", 
        subscribers: 29719687}, 
    {banner_background_color: "#0070c1", 
        banner_background_image: "https://styles.redditmedia.com/t5_2cneq/styles/bannerBackgroundImage_4vvj1k5ldn671.png?width=4000&amp;s=ed1d17ff05773b9a6a5f00c4cba0b009df46…", 
        banner_image: undefined, 
        description: "## **Welcome to /r/Politics! Please read [the wiki](/r/politics/w/index) before participating.** ||  [Voter Registratio…", 
        display_name_prefixed: "r/politics", 
        title: "Politics", 
        url: "/r/politics/", 
        created: 1186377399, 
        subreddit_type: "public", 
        community_icon: "https://styles.redditmedia.com/t5_2cneq/styles/communityIcon_fy84mdgh75201.jpg?width=256&amp;s=0842d327b6d42f0e432135c7f46030bd8db64e4b", 
        subscribers: 8773651}
];